# Generated by Django 2.2.4 on 2023-07-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20230707_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='c',
            field=models.IntegerField(default=0),
        ),
    ]
