# Generated by Django 2.2.4 on 2023-07-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20230708_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress',
            field=models.FloatField(default=0),
        ),
    ]
