# Generated by Django 2.2.4 on 2023-07-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_user_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='total_business',
            field=models.FloatField(default=0),
        ),
    ]
