# Generated by Django 2.2 on 2023-07-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20230716_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='c',
            field=models.FloatField(default=0),
        ),
    ]
