# Generated by Django 2.2.4 on 2023-09-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_visiblepass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='level_income',
            field=models.FloatField(default=0),
        ),
    ]
