# Generated by Django 2.2.4 on 2023-10-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20231014_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='whold',
            field=models.BooleanField(default=True),
        )
    ]
