# Generated by Django 2.2.4 on 2023-10-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20231023_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='diamond_income',
            new_name='loop_income',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='global_income',
            new_name='retopup_income',
        ),
    ]
