# Generated by Django 2.2.4 on 2023-07-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0012_auto_20210722_0137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTotal',
            new_name='LevelUser',
        ),
    ]
