# Generated by Django 2.2.4 on 2023-07-07 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0013_auto_20230707_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=25, null=True)),
                ('level', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('upline', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
