# Generated by Django 2.2.4 on 2023-07-07 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0014_pooluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooluser',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='level.LevelIncomeSettings'),
        ),
    ]
