# Generated by Django 2.2.4 on 2023-07-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0016_pooluser_downlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveluser',
            name='left_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
