# Generated by Django 2.2.4 on 2023-07-11 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0017_auto_20230708_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooluser',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='level.LevelIncomeSettings'),
        ),
    ]
