# Generated by Django 2.2.4 on 2023-07-15 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0018_auto_20230711_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelincomesettings',
            old_name='expiration_period',
            new_name='permanent_reward',
        ),
        migrations.RemoveField(
            model_name='levelincomesettings',
            name='return_amount',
        ),
        migrations.RemoveField(
            model_name='leveluser',
            name='left_months',
        ),
    ]
