# Generated by Django 2.2.4 on 2023-07-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0019_auto_20230715_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelincomesettings',
            name='permanent_reward',
            field=models.FloatField(),
        ),
    ]
