# Generated by Django 2.2.4 on 2023-07-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0020_auto_20230715_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelincomesettings',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
