# Generated by Django 2.2.4 on 2023-10-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0023_levelincomesettings_pool_roi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pooluser',
            name='d1',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pooluser',
            name='d2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='pooluser',
            name='d3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='leveluser',
            name='activated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='pooluser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='level.LevelIncomeSettings'),
        ),
        migrations.AlterField(
            model_name='pooluser',
            name='user',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pooluser',
            unique_together={('user', 'level')},
        ),
        migrations.RemoveField(
            model_name='pooluser',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pooluser',
            name='downlines',
        ),
        migrations.RemoveField(
            model_name='pooluser',
            name='plan',
        ),
    ]
