# Generated by Django 2.2.4 on 2023-10-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0024_auto_20231027_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooluser',
            name='d1',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pooluser',
            name='d2',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pooluser',
            name='d3',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pooluser',
            name='upline',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
