# Generated by Django 2.2.4 on 2023-10-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0025_auto_20231027_2130'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pooluser',
            unique_together=set(),
        ),
    ]
