# Generated by Django 2.2.4 on 2023-10-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210701_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_turnover', models.FloatField()),
                ('today_turnover', models.FloatField()),
            ],
        ),
    ]
