# Generated by Django 2.2.4 on 2023-10-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='today_new_ids',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
