# Generated by Django 2.2.4 on 2023-07-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0008_auto_20211130_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mtw',
            old_name='account_number',
            new_name='private_key',
        ),
        migrations.RenameField(
            model_name='mtw',
            old_name='ifsc',
            new_name='wallet_address',
        ),
        migrations.RemoveField(
            model_name='mtw',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mtw',
            name='status',
        ),
    ]
