# Generated by Django 2.2.4 on 2023-10-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0011_fundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=200),
        ),
    ]
